# Generated by Django 5.2.7 on 2025-11-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(default='Simulation SUMO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_simulation', models.FloatField(help_text='Durée totale (secondes)')),
                ('nb_vehicules_total', models.IntegerField(default=0)),
                ('nb_pietons_total', models.IntegerField(default=0)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='dashboard.simulation')),
            ],
        ),
    ]
