# Generated by Django 5.2.7 on 2025-11-23 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistique',
            name='directional_stats',
            field=models.JSONField(default=dict, help_text="Stats par direction: { 'N': {'mean_speed':..., 'occupancy':...}, ... }"),
        ),
        migrations.AddField(
            model_name='statistique',
            name='lanes_stats',
            field=models.JSONField(default=dict, help_text="Stats détaillées par lane: { 'lane_id': {'num_vehicles':..., 'mean_speed':..., 'occupancy':...}, ... }"),
        ),
        migrations.AddField(
            model_name='statistique',
            name='mean_speed_global',
            field=models.FloatField(default=0.0, help_text='Vitesse moyenne globale des voies'),
        ),
        migrations.AddField(
            model_name='statistique',
            name='occupancy_global',
            field=models.FloatField(default=0.0, help_text='Occupation moyenne globale des voies'),
        ),
    ]
